
dist:
  name: otelcol-suse-ai
  description: Minimal OTel Collector distribution for monitoring SUSE AI
  output_path: ./otelcol-suse-ai

exporters:
  - gomod:
      go.opentelemetry.io/collector/exporter/debugexporter v0.142.0
  - gomod:
      go.opentelemetry.io/collector/exporter/otlpexporter v0.142.0

processors:
  - gomod:
      go.opentelemetry.io/collector/processor/batchprocessor v0.142.0

receivers:
  - gomod:
      go.opentelemetry.io/collector/receiver/otlpreceiver v0.142.0

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.18.0
